name: mainline-workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages "https://suveenkumar.github.io/sh/"
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./altra.FE
        publish_branch: gh-pages
        user_name: Suveen Kumar
        user_email: suveenkumar1997@gmail.com